// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// O Lovable injeta automaticamente as variáveis do Supabase no build.
// Em desenvolvimento local, crie um .env com VITE_SUPABASE_URL e VITE_SUPABASE_PUBLISHABLE_KEY.
const SUPABASE_URL: string =
  (import.meta.env.VITE_SUPABASE_URL as string) ||
  (import.meta.env.APP_SUPABASE_URL as string) ||
  "";

const SUPABASE_PUBLISHABLE_KEY: string =
  (import.meta.env.VITE_SUPABASE_PUBLISHABLE_KEY as string) ||
  (import.meta.env.APP_SUPABASE_KEY as string) ||
  "";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
